package com.example.admin.weatherui.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.admin.weatherui.db.Cities;

import com.example.admin.weatherui.db.CitiesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig citiesDaoConfig;

    private final CitiesDao citiesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        citiesDaoConfig = daoConfigMap.get(CitiesDao.class).clone();
        citiesDaoConfig.initIdentityScope(type);

        citiesDao = new CitiesDao(citiesDaoConfig, this);

        registerDao(Cities.class, citiesDao);
    }
    
    public void clear() {
        citiesDaoConfig.clearIdentityScope();
    }

    public CitiesDao getCitiesDao() {
        return citiesDao;
    }

}
