package com.example.admin.weatherui.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.admin.weatherui.db.Cities;
import com.example.admin.weatherui.db.CurrentDetails;
import com.example.admin.weatherui.db.Currents;
import com.example.admin.weatherui.db.Hour;
import com.example.admin.weatherui.db.HoursDetails;
import com.example.admin.weatherui.db.WeatherIcons;
import com.example.admin.weatherui.db.Weeks;
import com.example.admin.weatherui.db.WeeksDetails;

import com.example.admin.weatherui.db.CitiesDao;
import com.example.admin.weatherui.db.CurrentDetailsDao;
import com.example.admin.weatherui.db.CurrentsDao;
import com.example.admin.weatherui.db.HourDao;
import com.example.admin.weatherui.db.HoursDetailsDao;
import com.example.admin.weatherui.db.WeatherIconsDao;
import com.example.admin.weatherui.db.WeeksDao;
import com.example.admin.weatherui.db.WeeksDetailsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig citiesDaoConfig;
    private final DaoConfig currentDetailsDaoConfig;
    private final DaoConfig currentsDaoConfig;
    private final DaoConfig hourDaoConfig;
    private final DaoConfig hoursDetailsDaoConfig;
    private final DaoConfig weatherIconsDaoConfig;
    private final DaoConfig weeksDaoConfig;
    private final DaoConfig weeksDetailsDaoConfig;

    private final CitiesDao citiesDao;
    private final CurrentDetailsDao currentDetailsDao;
    private final CurrentsDao currentsDao;
    private final HourDao hourDao;
    private final HoursDetailsDao hoursDetailsDao;
    private final WeatherIconsDao weatherIconsDao;
    private final WeeksDao weeksDao;
    private final WeeksDetailsDao weeksDetailsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        citiesDaoConfig = daoConfigMap.get(CitiesDao.class).clone();
        citiesDaoConfig.initIdentityScope(type);

        currentDetailsDaoConfig = daoConfigMap.get(CurrentDetailsDao.class).clone();
        currentDetailsDaoConfig.initIdentityScope(type);

        currentsDaoConfig = daoConfigMap.get(CurrentsDao.class).clone();
        currentsDaoConfig.initIdentityScope(type);

        hourDaoConfig = daoConfigMap.get(HourDao.class).clone();
        hourDaoConfig.initIdentityScope(type);

        hoursDetailsDaoConfig = daoConfigMap.get(HoursDetailsDao.class).clone();
        hoursDetailsDaoConfig.initIdentityScope(type);

        weatherIconsDaoConfig = daoConfigMap.get(WeatherIconsDao.class).clone();
        weatherIconsDaoConfig.initIdentityScope(type);

        weeksDaoConfig = daoConfigMap.get(WeeksDao.class).clone();
        weeksDaoConfig.initIdentityScope(type);

        weeksDetailsDaoConfig = daoConfigMap.get(WeeksDetailsDao.class).clone();
        weeksDetailsDaoConfig.initIdentityScope(type);

        citiesDao = new CitiesDao(citiesDaoConfig, this);
        currentDetailsDao = new CurrentDetailsDao(currentDetailsDaoConfig, this);
        currentsDao = new CurrentsDao(currentsDaoConfig, this);
        hourDao = new HourDao(hourDaoConfig, this);
        hoursDetailsDao = new HoursDetailsDao(hoursDetailsDaoConfig, this);
        weatherIconsDao = new WeatherIconsDao(weatherIconsDaoConfig, this);
        weeksDao = new WeeksDao(weeksDaoConfig, this);
        weeksDetailsDao = new WeeksDetailsDao(weeksDetailsDaoConfig, this);

        registerDao(Cities.class, citiesDao);
        registerDao(CurrentDetails.class, currentDetailsDao);
        registerDao(Currents.class, currentsDao);
        registerDao(Hour.class, hourDao);
        registerDao(HoursDetails.class, hoursDetailsDao);
        registerDao(WeatherIcons.class, weatherIconsDao);
        registerDao(Weeks.class, weeksDao);
        registerDao(WeeksDetails.class, weeksDetailsDao);
    }
    
    public void clear() {
        citiesDaoConfig.clearIdentityScope();
        currentDetailsDaoConfig.clearIdentityScope();
        currentsDaoConfig.clearIdentityScope();
        hourDaoConfig.clearIdentityScope();
        hoursDetailsDaoConfig.clearIdentityScope();
        weatherIconsDaoConfig.clearIdentityScope();
        weeksDaoConfig.clearIdentityScope();
        weeksDetailsDaoConfig.clearIdentityScope();
    }

    public CitiesDao getCitiesDao() {
        return citiesDao;
    }

    public CurrentDetailsDao getCurrentDetailsDao() {
        return currentDetailsDao;
    }

    public CurrentsDao getCurrentsDao() {
        return currentsDao;
    }

    public HourDao getHourDao() {
        return hourDao;
    }

    public HoursDetailsDao getHoursDetailsDao() {
        return hoursDetailsDao;
    }

    public WeatherIconsDao getWeatherIconsDao() {
        return weatherIconsDao;
    }

    public WeeksDao getWeeksDao() {
        return weeksDao;
    }

    public WeeksDetailsDao getWeeksDetailsDao() {
        return weeksDetailsDao;
    }

}
