package com.example.admin.weatherui.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOURS_DETAILS".
*/
public class HoursDetailsDao extends AbstractDao<HoursDetails, Long> {

    public static final String TABLENAME = "HOURS_DETAILS";

    /**
     * Properties of entity HoursDetails.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Wind_cdir = new Property(1, String.class, "wind_cdir", false, "WIND_CDIR");
        public final static Property Rh = new Property(2, double.class, "rh", false, "RH");
        public final static Property Wind_spd = new Property(3, double.class, "wind_spd", false, "WIND_SPD");
        public final static Property Pop = new Property(4, double.class, "pop", false, "POP");
        public final static Property Wind_cdir_full = new Property(5, String.class, "wind_cdir_full", false, "WIND_CDIR_FULL");
        public final static Property App_temp = new Property(6, double.class, "app_temp", false, "APP_TEMP");
        public final static Property Pres = new Property(7, double.class, "pres", false, "PRES");
        public final static Property Dewpt = new Property(8, double.class, "dewpt", false, "DEWPT");
        public final static Property Snow = new Property(9, double.class, "snow", false, "SNOW");
        public final static Property Uv = new Property(10, double.class, "uv", false, "UV");
        public final static Property Wind_dir = new Property(11, double.class, "wind_dir", false, "WIND_DIR");
        public final static Property Pod = new Property(12, String.class, "pod", false, "POD");
        public final static Property Dhi = new Property(13, double.class, "dhi", false, "DHI");
        public final static Property Ts = new Property(14, int.class, "ts", false, "TS");
        public final static Property Snow_depth = new Property(15, double.class, "snow_depth", false, "SNOW_DEPTH");
        public final static Property Precip = new Property(16, double.class, "precip", false, "PRECIP");
        public final static Property Datetime = new Property(17, String.class, "datetime", false, "DATETIME");
        public final static Property Temp = new Property(18, double.class, "temp", false, "TEMP");
        public final static Property Slp = new Property(19, double.class, "slp", false, "SLP");
        public final static Property Clouds = new Property(20, double.class, "clouds", false, "CLOUDS");
        public final static Property Vis = new Property(21, double.class, "vis", false, "VIS");
        public final static Property Snow6h = new Property(22, double.class, "snow6h", false, "SNOW6H");
        public final static Property Precip6h = new Property(23, double.class, "precip6h", false, "PRECIP6H");
        public final static Property HourId = new Property(24, long.class, "hourId", false, "HOUR_ID");
        public final static Property WeatherIconsId = new Property(25, long.class, "weatherIconsId", false, "WEATHER_ICONS_ID");
    }

    private DaoSession daoSession;

    private Query<HoursDetails> hour_DataQuery;

    public HoursDetailsDao(DaoConfig config) {
        super(config);
    }
    
    public HoursDetailsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOURS_DETAILS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"WIND_CDIR\" TEXT," + // 1: wind_cdir
                "\"RH\" REAL NOT NULL ," + // 2: rh
                "\"WIND_SPD\" REAL NOT NULL ," + // 3: wind_spd
                "\"POP\" REAL NOT NULL ," + // 4: pop
                "\"WIND_CDIR_FULL\" TEXT," + // 5: wind_cdir_full
                "\"APP_TEMP\" REAL NOT NULL ," + // 6: app_temp
                "\"PRES\" REAL NOT NULL ," + // 7: pres
                "\"DEWPT\" REAL NOT NULL ," + // 8: dewpt
                "\"SNOW\" REAL NOT NULL ," + // 9: snow
                "\"UV\" REAL NOT NULL ," + // 10: uv
                "\"WIND_DIR\" REAL NOT NULL ," + // 11: wind_dir
                "\"POD\" TEXT," + // 12: pod
                "\"DHI\" REAL NOT NULL ," + // 13: dhi
                "\"TS\" INTEGER NOT NULL ," + // 14: ts
                "\"SNOW_DEPTH\" REAL NOT NULL ," + // 15: snow_depth
                "\"PRECIP\" REAL NOT NULL ," + // 16: precip
                "\"DATETIME\" TEXT," + // 17: datetime
                "\"TEMP\" REAL NOT NULL ," + // 18: temp
                "\"SLP\" REAL NOT NULL ," + // 19: slp
                "\"CLOUDS\" REAL NOT NULL ," + // 20: clouds
                "\"VIS\" REAL NOT NULL ," + // 21: vis
                "\"SNOW6H\" REAL NOT NULL ," + // 22: snow6h
                "\"PRECIP6H\" REAL NOT NULL ," + // 23: precip6h
                "\"HOUR_ID\" INTEGER NOT NULL ," + // 24: hourId
                "\"WEATHER_ICONS_ID\" INTEGER NOT NULL );"); // 25: weatherIconsId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOURS_DETAILS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HoursDetails entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String wind_cdir = entity.getWind_cdir();
        if (wind_cdir != null) {
            stmt.bindString(2, wind_cdir);
        }
        stmt.bindDouble(3, entity.getRh());
        stmt.bindDouble(4, entity.getWind_spd());
        stmt.bindDouble(5, entity.getPop());
 
        String wind_cdir_full = entity.getWind_cdir_full();
        if (wind_cdir_full != null) {
            stmt.bindString(6, wind_cdir_full);
        }
        stmt.bindDouble(7, entity.getApp_temp());
        stmt.bindDouble(8, entity.getPres());
        stmt.bindDouble(9, entity.getDewpt());
        stmt.bindDouble(10, entity.getSnow());
        stmt.bindDouble(11, entity.getUv());
        stmt.bindDouble(12, entity.getWind_dir());
 
        String pod = entity.getPod();
        if (pod != null) {
            stmt.bindString(13, pod);
        }
        stmt.bindDouble(14, entity.getDhi());
        stmt.bindLong(15, entity.getTs());
        stmt.bindDouble(16, entity.getSnow_depth());
        stmt.bindDouble(17, entity.getPrecip());
 
        String datetime = entity.getDatetime();
        if (datetime != null) {
            stmt.bindString(18, datetime);
        }
        stmt.bindDouble(19, entity.getTemp());
        stmt.bindDouble(20, entity.getSlp());
        stmt.bindDouble(21, entity.getClouds());
        stmt.bindDouble(22, entity.getVis());
        stmt.bindDouble(23, entity.getSnow6h());
        stmt.bindDouble(24, entity.getPrecip6h());
        stmt.bindLong(25, entity.getHourId());
        stmt.bindLong(26, entity.getWeatherIconsId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HoursDetails entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String wind_cdir = entity.getWind_cdir();
        if (wind_cdir != null) {
            stmt.bindString(2, wind_cdir);
        }
        stmt.bindDouble(3, entity.getRh());
        stmt.bindDouble(4, entity.getWind_spd());
        stmt.bindDouble(5, entity.getPop());
 
        String wind_cdir_full = entity.getWind_cdir_full();
        if (wind_cdir_full != null) {
            stmt.bindString(6, wind_cdir_full);
        }
        stmt.bindDouble(7, entity.getApp_temp());
        stmt.bindDouble(8, entity.getPres());
        stmt.bindDouble(9, entity.getDewpt());
        stmt.bindDouble(10, entity.getSnow());
        stmt.bindDouble(11, entity.getUv());
        stmt.bindDouble(12, entity.getWind_dir());
 
        String pod = entity.getPod();
        if (pod != null) {
            stmt.bindString(13, pod);
        }
        stmt.bindDouble(14, entity.getDhi());
        stmt.bindLong(15, entity.getTs());
        stmt.bindDouble(16, entity.getSnow_depth());
        stmt.bindDouble(17, entity.getPrecip());
 
        String datetime = entity.getDatetime();
        if (datetime != null) {
            stmt.bindString(18, datetime);
        }
        stmt.bindDouble(19, entity.getTemp());
        stmt.bindDouble(20, entity.getSlp());
        stmt.bindDouble(21, entity.getClouds());
        stmt.bindDouble(22, entity.getVis());
        stmt.bindDouble(23, entity.getSnow6h());
        stmt.bindDouble(24, entity.getPrecip6h());
        stmt.bindLong(25, entity.getHourId());
        stmt.bindLong(26, entity.getWeatherIconsId());
    }

    @Override
    protected final void attachEntity(HoursDetails entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HoursDetails readEntity(Cursor cursor, int offset) {
        HoursDetails entity = new HoursDetails( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // wind_cdir
            cursor.getDouble(offset + 2), // rh
            cursor.getDouble(offset + 3), // wind_spd
            cursor.getDouble(offset + 4), // pop
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // wind_cdir_full
            cursor.getDouble(offset + 6), // app_temp
            cursor.getDouble(offset + 7), // pres
            cursor.getDouble(offset + 8), // dewpt
            cursor.getDouble(offset + 9), // snow
            cursor.getDouble(offset + 10), // uv
            cursor.getDouble(offset + 11), // wind_dir
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // pod
            cursor.getDouble(offset + 13), // dhi
            cursor.getInt(offset + 14), // ts
            cursor.getDouble(offset + 15), // snow_depth
            cursor.getDouble(offset + 16), // precip
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // datetime
            cursor.getDouble(offset + 18), // temp
            cursor.getDouble(offset + 19), // slp
            cursor.getDouble(offset + 20), // clouds
            cursor.getDouble(offset + 21), // vis
            cursor.getDouble(offset + 22), // snow6h
            cursor.getDouble(offset + 23), // precip6h
            cursor.getLong(offset + 24), // hourId
            cursor.getLong(offset + 25) // weatherIconsId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HoursDetails entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setWind_cdir(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRh(cursor.getDouble(offset + 2));
        entity.setWind_spd(cursor.getDouble(offset + 3));
        entity.setPop(cursor.getDouble(offset + 4));
        entity.setWind_cdir_full(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setApp_temp(cursor.getDouble(offset + 6));
        entity.setPres(cursor.getDouble(offset + 7));
        entity.setDewpt(cursor.getDouble(offset + 8));
        entity.setSnow(cursor.getDouble(offset + 9));
        entity.setUv(cursor.getDouble(offset + 10));
        entity.setWind_dir(cursor.getDouble(offset + 11));
        entity.setPod(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setDhi(cursor.getDouble(offset + 13));
        entity.setTs(cursor.getInt(offset + 14));
        entity.setSnow_depth(cursor.getDouble(offset + 15));
        entity.setPrecip(cursor.getDouble(offset + 16));
        entity.setDatetime(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setTemp(cursor.getDouble(offset + 18));
        entity.setSlp(cursor.getDouble(offset + 19));
        entity.setClouds(cursor.getDouble(offset + 20));
        entity.setVis(cursor.getDouble(offset + 21));
        entity.setSnow6h(cursor.getDouble(offset + 22));
        entity.setPrecip6h(cursor.getDouble(offset + 23));
        entity.setHourId(cursor.getLong(offset + 24));
        entity.setWeatherIconsId(cursor.getLong(offset + 25));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HoursDetails entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HoursDetails entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HoursDetails entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "data" to-many relationship of Hour. */
    public List<HoursDetails> _queryHour_Data(long hourId) {
        synchronized (this) {
            if (hour_DataQuery == null) {
                QueryBuilder<HoursDetails> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.HourId.eq(null));
                hour_DataQuery = queryBuilder.build();
            }
        }
        Query<HoursDetails> query = hour_DataQuery.forCurrentThread();
        query.setParameter(0, hourId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getWeatherIconsDao().getAllColumns());
            builder.append(" FROM HOURS_DETAILS T");
            builder.append(" LEFT JOIN WEATHER_ICONS T0 ON T.\"WEATHER_ICONS_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected HoursDetails loadCurrentDeep(Cursor cursor, boolean lock) {
        HoursDetails entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        WeatherIcons weatherIcons = loadCurrentOther(daoSession.getWeatherIconsDao(), cursor, offset);
         if(weatherIcons != null) {
            entity.setWeatherIcons(weatherIcons);
        }

        return entity;    
    }

    public HoursDetails loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<HoursDetails> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<HoursDetails> list = new ArrayList<HoursDetails>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<HoursDetails> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<HoursDetails> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
